language: python
sudo: required
dist: xenial

env:
  - FLASK=1.0
  - FLASK=0.12
  - FLASK=0.11
  - FLASK=0.10

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7

before_install:
  - pip install coveralls

install:
  - pip install flask==$FLASK
  - pip install .

script:
  - coverage run --source flask_gopher setup.py test

after_success:
  - coveralls
